# Generated by Django 4.2.7 on 2025-10-20 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this job search query', max_length=200)),
                ('keyword', models.CharField(blank=True, help_text='Job keyword to search for', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location to search in', max_length=200)),
                ('date_since_posted', models.CharField(blank=True, help_text='Date filter: past month, past week, 24hr', max_length=50)),
                ('job_type', models.CharField(blank=True, help_text='Job type: full time, part time, contract, etc.', max_length=50)),
                ('remote_filter', models.CharField(blank=True, help_text='Remote filter: on-site, remote, hybrid', max_length=50)),
                ('salary', models.CharField(blank=True, help_text='Minimum salary: 40000, 60000, 80000, 100000, 120000', max_length=50)),
                ('experience_level', models.CharField(blank=True, help_text='Experience level: internship, entry level, associate, etc.', max_length=50)),
                ('limit', models.IntegerField(default=25, help_text='Maximum number of jobs to return')),
                ('sort_by', models.CharField(blank=True, help_text='Sort by: recent, relevant', max_length=50)),
                ('has_verification', models.BooleanField(default=False, help_text='Only verified companies')),
                ('under_10_applicants', models.BooleanField(default=False, help_text='Under 10 applicants')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('custom_schedule', models.CharField(blank=True, help_text='Custom cron expression (if frequency is custom)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this query is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Query',
                'verbose_name_plural': 'Job Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_posted', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('job_url', models.URLField(unique=True)),
                ('company_logo', models.URLField(blank=True)),
                ('ago_time', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=500)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('posted_date', models.CharField(blank=True, max_length=100)),
                ('applicant_count', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('seniority_level', models.CharField(blank=True, max_length=100)),
                ('job_function', models.CharField(blank=True, max_length=200)),
                ('industries', models.CharField(blank=True, max_length=200)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('details_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('details_scraped', models.BooleanField(default=False)),
                ('job_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobquery')),
            ],
            options={
                'verbose_name': 'Job Detail',
                'verbose_name_plural': 'Job Details',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
