# Generated by Django 4.2.7 on 2025-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='linkedin_job_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='job_url',
            field=models.URLField(),
        ),
    ]
