# Generated by Django 4.2.7 on 2025-10-24 18:25

from django.db import migrations
import re


def populate_linkedin_job_ids(apps, schema_editor):
    """Populate LinkedIn job IDs for existing records"""
    JobDetail = apps.get_model('jobs', 'JobDetail')
    
    def extract_linkedin_job_id(job_url):
        """Extract LinkedIn job ID from URL using regex"""
        if not job_url:
            return None
            
        # Regex pattern to match the job ID at the end of the job title
        # Matches: -{digits} followed by ? or / or end of string
        pattern = r'-(\d+)(?:\?|/|$)'
        match = re.search(pattern, job_url)
        
        if match:
            return match.group(1)
        return None
    
    # Update all existing records
    for job in JobDetail.objects.all():
        if not job.linkedin_job_id:
            job.linkedin_job_id = extract_linkedin_job_id(job.job_url)
            job.save()


def reverse_populate_linkedin_job_ids(apps, schema_editor):
    """Reverse migration - clear LinkedIn job IDs"""
    JobDetail = apps.get_model('jobs', 'JobDetail')
    JobDetail.objects.all().update(linkedin_job_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobdetail_linkedin_job_id_alter_jobdetail_job_url'),
    ]

    operations = [
        migrations.RunPython(populate_linkedin_job_ids, reverse_populate_linkedin_job_ids),
    ]
