# Generated by Django 4.2.7 on 2025-10-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20251024_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='is_reposted',
            field=models.BooleanField(default=False, help_text='Whether this job was reposted'),
        ),
        migrations.AlterField(
            model_name='jobquery',
            name='date_since_posted',
            field=models.CharField(blank=True, help_text="Date filter: 'past month', 'past week', '24hr' (LinkedIn API only supports these 3 options)", max_length=50),
        ),
    ]
