# Generated by Django 4.2.7 on 2025-10-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobdetail_is_reposted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='is_reposted',
        ),
    ]
